version: "3.8"

volumes:
  local-go-chat-data:

services:
  db:
    image: mongo:5.0.0-rc3-focal
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: chat
      MONGO_INITDB_DATABASE: chat
    volumes:
      - local-go-chat-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: chat
    depends_on:
      - db
